In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("billets.csv", sep =';')
df.head()

,y = is_genuine,diagonal,height_left,height_right,margin_low,margin_up,length
0,True,171.81,104.86,104.95,4.52,2.89,112.83
1,True,171.46,103.36,103.66,3.77,2.99,113.09
2,True,172.69,104.48,103.50,4.40,2.94,113.16
3,True,171.36,103.91,103.94,3.62,3.01,113.51
4,True,171.73,104.28,103.46,4.04,3.48,112.54

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   y = is_genuine  1500 non-null   bool
 1   diagonal        1500 non-null   float64
 2   height_left     1500 non-null   float64
 3   height_right    1500 non-null   float64
 4   margin_low      1463 non-null   float64
 5   margin_up       1500 non-null   float64
 6   length          1500 non-null   float64
dtypes: bool(1), float64(6)
memory usage: 71.9 KB

In [4]:
df.describe(include=bool)

       y = is_genuine
count            1500
unique              2
top              True
freq             1000

In [5]:
df.describe()

,diagonal,height_left,height_right,margin_low,margin_up,length
count,1500.000000,1500.000000,1500.000000,1463.000000,1500.000000,1500.00000
mean,171.958440,104.029533,103.920307,4.485967,3.151473,112.67850
std,0.305195,0.299462,0.325627,0.663813,0.231813,0.87273
min,171.040000,103.140000,102.820000,2.980000,2.270000,109.49000
25%,171.750000,103.820000,103.710000,4.015000,2.990000,112.03000
50%,171.960000,104.040000,103.920000,4.310000,3.140000,112.96000
75%,172.170000,104.230000,104.150000,4.870000,3.310000,113.34000
max,173.010000,104.880000,104.950000,6.900000,3.910000,114.44000

In [6]:
df.isnull().sum()

y = is_genuine     0
diagonal           0
height_left        0
height_right       0
margin_low        37
margin_up          0
length             0
dtype: int64

In [7]:
#imputauions des valeurs nul 
df.fillna(0,inplace=True)

In [8]:
df.columns

Index(['y = is_genuine', 'diagonal', 'height_left', 'height_right',
       'margin_low', 'margin_up', 'length'],
      dtype='object')

In [9]:
x=df[['diagonal', 'height_left', 'height_right','margin_low', 'margin_up', 'length']]
y=x=df[['y = is_genuine']]

In [ ]:
# 1 Lectures des données
# 2 Analyse descriptive et nettoyage


# 5 Évaluation du modèle
# 6 Prédiction
# 7 Visualisation des résultats

In [ ]:
# 3 Séparation des données en ensembles d'apprentissage et de test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [11]:
# 4 Modélisation

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

c:\Users\mariy\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [12]:
y_pred = model.predict(X_test)
y_pred

array([False, False,  True,  True,  True,  True, False,  True, False,
        True,  True, False,  True, False,  True, False, False,  True,
        True,  True, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False, False,  True,  True,
        True,  True, False,  True, False,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False, False,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True, False, False,  True,  True, False,
       False,  True, False,  True, False,  True, False, False,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True, False,  True, False,  True,  True, False, False,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
       False, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
       False,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True, False, False, False,  True,  True, False,
       False, False, False, False, False, False,  True, False,  True,
        True,  True,  True, False, False, False,  True, False,  True,
       False,  True, False,  True,  True,  True,  True, False, False,
        True,  True,  True, False, False,  True,  True, False,  True,
        True,  True,  True, False,  True, False, False, False,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True, False,  True, False,  True, False,  True,  True,  True,
       False, False,  True])

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score
print(confusion_matrix(y_test, y_pred))

[[110   0]
 [  0 190]]

In [14]:
precision_score(y_test, y_pred)

1.0

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score, confusion_matrix

# Création du modèle kNN avec distance euclidienne
knn = KNeighborsClassifier (n_neighbors=5, metric="minkowski", p=2)

# Nombre de voisins
#metric='minkowski, 
# Distance Minkowski p=2
# p=2 → distance euclidienne

# Entrainement
knn.fit(X_train, y_train)

# Prédiction
y_pred = knn.predict(X_test)

#Évaluation
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print("Accuracy:", acc)
print("Matrice de Confusion:\n",cm)

Accuracy: 1.0
Matrice de Confusion:
 [[110   0]
 [  0 190]]

c:\Users\mariy\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

: